{{- if .Values.secret.enabled }}
apiVersion: v1
data:
  secret-key: {{ .Values.secret.secretKey }}
kind: Secret
metadata:
  name: ai-backend-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
{{- end}}