apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sgpt-rolebinding
  namespace: k8sgpt
subjects:
- kind: ServiceAccount
  name: k8sgpt
  namespace: k8sgpt
roleRef:
  kind: ClusterRole
  name: k8sgpt-cluster-role-all
  apiGroup: rbac.authorization.k8s.io