apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-service
  namespace: k8sgpt
spec:
  selector:
    app: k8sgpt
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
