apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: k8sgpt
  name: k8sgpt-service-monitor
  namespace: k8sgpt
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: k8sgpt
