name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    GO_VERSION: "~1.20"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Unit Test
        run: make test

      # - name: Fmt Test
      #   run: fmtFiles=$(make fmt); if [ "$fmtFiles" != "" ];then exit 1; fi

